name: Builder

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  ubuntu1604:
    runs-on: ubuntu-16.04

    env:
      NCNN_VERSION: 20210322
      CPU_PKG_NAME: ncnn-20210322-ubuntu1604
      GPU_PKG_NAME: ncnn-20210322-ubuntu1604-vulkan
      CV_VERSION: 4.5.1
      CV_PKG_NAME: opencv-4.5.1-ubuntu1604

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 安装vulkan
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.162.0/linux/vulkansdk-linux-x86_64-1.2.162.0.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.2.162.0.tar.gz
          tar -xf vulkansdk-linux-x86_64-1.2.162.0.tar.gz
          rm -rf 1.2.162.0/source 1.2.162.0/samples
          find 1.2.162.0 -type f | grep -v -E 'vulkan|glslang' | xargs rm

      # 缓存vulkan
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: "1.2.162.0"
          key: vulkansdk-linux-x86_64-1.2.162.0

      # 下载ncnn-static
      - name: download ncnn-static
        run: |
          cd ncnn-static
          wget https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.CPU_PKG_NAME }}.7z -O ${{ env.CPU_PKG_NAME }}.7z
          7z x ${{ env.CPU_PKG_NAME }}.7z -aoa

      # 下载ncnn-vulkan-static
      - name: download ncnn-vulkan-static
        run: |
          cd ncnn-vulkan-static
          wget https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.GPU_PKG_NAME }}.7z -O ${{ env.GPU_PKG_NAME }}.7z
          7z x ${{ env.GPU_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          wget https://github.com/RapidOCR/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -O ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          export VULKAN_SDK=`pwd`/1.2.162.0/x86_64
          chmod a+x build-default.sh &&./build-default.sh

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir linux-bin
          mv Linux-bin-cpu/install/bin linux-bin/Linux-bin-cpu
          mv Linux-bin-gpu/install/bin linux-bin/Linux-bin-gpu
          7z a linux-bin.7z linux-bin
          mkdir linux-jni
          mv Linux-jni-cpu/install/sharedlib linux-jni/Linux-jni-cpu
          mv Linux-jni-gpu/install/sharedlib linux-jni/Linux-jni-gpu
          7z a linux-jni.7z linux-jni

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: linux-bin
          path: linux-bin.7z

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: linux-jni
          path: linux-jni.7z

  macos1015:
    runs-on: macos-latest

    env:
      NCNN_VERSION: 20210322
      CPU_PKG_NAME: ncnn-20210322-macos1015
      GPU_PKG_NAME: ncnn-20210322-macos1015-vulkan
      CV_VERSION: 4.5.1
      CV_PKG_NAME: opencv-4.5.1-macos1015

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 安装openmp
      - name: install openmp
        run: |
          brew install libomp

      # 安装vulkan
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.162.0/mac/vulkansdk-macos-1.2.162.0.dmg?Human=true -O vulkansdk-macos-1.2.162.0.dmg
          hdiutil attach vulkansdk-macos-1.2.162.0.dmg
          cp -r /Volumes/vulkansdk-macos-1.2.162.0 .
          rm -rf vulkansdk-macos-1.2.162.0/Applications
          find vulkansdk-macos-1.2.162.0 -type f | grep -v -E 'vulkan|glslang|MoltenVK' | xargs rm
          hdiutil detach /Volumes/vulkansdk-macos-1.2.162.0

      # 缓存vulkan
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: vulkansdk-macos-1.2.162.0
          key: vulkansdk-macos-1.2.162.0

      # 下载ncnn-static
      - name: download ncnn-static
        run: |
          cd ncnn-static
          wget https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.CPU_PKG_NAME }}.7z -O ${{ env.CPU_PKG_NAME }}.7z
          7z x ${{ env.CPU_PKG_NAME }}.7z -aoa

      # 下载ncnn-vulkan-static
      - name: download ncnn-vulkan-static
        run: |
          cd ncnn-vulkan-static
          wget https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.GPU_PKG_NAME }}.7z -O ${{ env.GPU_PKG_NAME }}.7z
          7z x ${{ env.GPU_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          wget https://github.com/RapidOCR/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -O ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          export VULKAN_SDK=`pwd`/vulkansdk-macos-1.2.162.0/macOS
          chmod a+x build-default.sh &&./build-default.sh

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir macos-bin
          mv Darwin-bin-cpu/install/bin macos-bin/Darwin-bin-cpu
          mv Darwin-bin-gpu/install/bin macos-bin/Darwin-bin-gpu
          7z a macos-bin.7z macos-bin
          mkdir macos-jni
          mv Darwin-jni-cpu/install/sharedlib macos-jni/Darwin-jni-cpu
          mv Darwin-jni-gpu/install/sharedlib macos-jni/Darwin-jni-gpu
          7z a macos-jni.7z macos-jni

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: macos-bin
          path: macos-bin.7z

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: macos-jni
          path: macos-jni.7z

  windows-vs2017:
    runs-on: windows-2016

    env:
      NCNN_VERSION: 20210322
      CPU_PKG_NAME: ncnn-20210322-windows-vs2017
      GPU_PKG_NAME: ncnn-20210322-windows-vs2017-vulkan
      CV_VERSION: 4.5.1
      CV_PKG_NAME: opencv-4.5.1-windows-vs2017

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 安装vulkan
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.162.0/windows/VulkanSDK-1.2.162.0-Installer.exe?Human=true -OutFile VulkanSDK-1.2.162.0-Installer.exe
          7z x -aoa ./VulkanSDK-1.2.162.0-Installer.exe -oVulkanSDK
          Remove-Item .\VulkanSDK\Demos, .\VulkanSDK\Samples, .\VulkanSDK\Third-Party, .\VulkanSDK\Tools, .\VulkanSDK\Tools32 -Recurse

      # 缓存vulkan
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1.0.3
        with:
          path: "VulkanSDK"
          key: VulkanSDK-1.2.162.0-Installer

      # 下载ncnn-static
      - name: download ncnn-static
        run: |
          cd ncnn-static
          Invoke-WebRequest -Uri https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.CPU_PKG_NAME }}.7z -OutFile ${{ env.CPU_PKG_NAME }}.7z
          7z x ${{ env.CPU_PKG_NAME }}.7z -aoa

      # 下载ncnn-vulkan-static
      - name: download ncnn-vulkan-static
        run: |
          cd ncnn-vulkan-static
          Invoke-WebRequest -Uri https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.GPU_PKG_NAME }}.7z -OutFile ${{ env.GPU_PKG_NAME }}.7z
          7z x ${{ env.GPU_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          Invoke-WebRequest -Uri https://github.com/RapidOCR/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -OutFile ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          $env:VULKAN_SDK="$(pwd)/VulkanSDK"
          ./build-default.bat

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir windows-bin
          mv win-bin-x64-cpu/install/bin windows-bin/win-bin-x64-cpu
          mv win-bin-x86-cpu/install/bin windows-bin/win-bin-x86-cpu
          mv win-jni-x64-cpu/install/bin windows-bin/win-jni-x64-cpu
          mv win-jni-x86-cpu/install/bin windows-bin/win-jni-x86-cpu
          7z a windows-bin.7z windows-bin
          mkdir windows-jni
          mv win-bin-x64-gpu/install/bin windows-jni/win-bin-x64-gpu
          mv win-bin-x86-gpu/install/bin windows-jni/win-bin-x86-gpu
          mv win-jni-x64-gpu/install/bin windows-jni/win-jni-x64-gpu
          mv win-jni-x86-gpu/install/bin windows-jni/win-jni-x86-gpu
          7z a windows-jni.7z windows-jni

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: windows-bin
          path: windows-bin.7z

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: windows-jni
          path: windows-jni.7z

  release:
    needs: [ ubuntu1604, macos1015, windows-vs2017 ]

    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 获取所有的git log和tag
      - name: Unshallow
        run: git fetch --prune --unshallow

      # 获取git log 从 previousTag 到 lastTag
      - name: Get git log
        id: git-log
        run: |
          previousTag=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          lastTag=$(git describe --abbrev=0 --tags)
          echo "previousTag:$previousTag ~ lastTag:$lastTag"
          log=$(git log $previousTag..$lastTag --pretty=format:'- %cd %an: %s\n' --date=format:'%Y-%m-%d %H:%M:%S')
          echo "$log"
          echo "::set-output name=log::"$log""

      # 创建Changelog文件 triggered by git tag push
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo -e '${{ steps.git-log.outputs.log }}' > Release.txt

      # Cat Changelog triggered by git tag push
      - name: Cat Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cat Release.txt

      # 下载artifact
      - name: download
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      # 查看artifact
      - name: list artifact
        run: |
          tree artifacts

      # 创建release
      - name: create-release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: Release.txt
          draft: false
          prerelease: false

      - name: upload-linux-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: linux-bin
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-linux-jni
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: linux-jni
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-macos-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: macos-bin
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-macos-jni
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: macos-jni
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: windows-bin
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      - name: upload-windows-jni
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: windows-jni
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ env.PKG_NAME }}/${{ env.PKG_NAME }}.7z
          asset_name: ${{ env.PKG_NAME }}.7z
          asset_content_type: application/x-7z-compressed

      # 获取指定时区的时间
      # https://github.com/marketplace/actions/get-time-action
      - name: Get Time
        id: time
        uses: JantHsueh/get-time-action@master
        with:
          timeZone: 8

      # 向钉钉发送消息
      # https://github.com/marketplace/actions/web-request-action
      - name: dingtalk
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          method: POST
          payload: '{"msgtype": "text", "text": {"content": "版本更新: ${{ github.repository }}-版本号: ${{ github.ref }} \n 编译时间： ${{ steps.time.outputs.time }} \n 距上个正式版的更新记录: \n${{ steps.git-log.outputs.log }}"}}'
          headers: '{"Content-Type": "application/json"}'