name: macos

on:
  workflow_dispatch:

jobs:
  macos1015:
    runs-on: macos-latest

    env:
      NCNN_VERSION: 20210322
      CPU_PKG_NAME: ncnn-20210322-macos1015
      GPU_PKG_NAME: ncnn-20210322-macos1015-vulkan
      CV_VERSION: 4.5.1
      CV_PKG_NAME: opencv-4.5.1-macos1015

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 安装openmp
      - name: install openmp
        run: |
          brew install libomp

      # 安装vulkan
      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.2.162.0/mac/vulkansdk-macos-1.2.162.0.dmg?Human=true -O vulkansdk-macos-1.2.162.0.dmg
          hdiutil attach vulkansdk-macos-1.2.162.0.dmg
          cp -r /Volumes/vulkansdk-macos-1.2.162.0 .
          rm -rf vulkansdk-macos-1.2.162.0/Applications
          find vulkansdk-macos-1.2.162.0 -type f | grep -v -E 'vulkan|glslang|MoltenVK' | xargs rm
          hdiutil detach /Volumes/vulkansdk-macos-1.2.162.0

      # 缓存vulkan
      - name: cache-vulkansdk
        id: cache-vulkansdk
        uses: actions/cache@v1
        with:
          path: vulkansdk-macos-1.2.162.0
          key: vulkansdk-macos-1.2.162.0

      # 下载ncnn-static
      - name: download ncnn-static
        run: |
          cd ncnn-static
          wget https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.CPU_PKG_NAME }}.7z -O ${{ env.CPU_PKG_NAME }}.7z
          7z x ${{ env.CPU_PKG_NAME }}.7z -aoa

      # 下载ncnn-vulkan-static
      - name: download ncnn-vulkan-static
        run: |
          cd ncnn-vulkan-static
          wget https://github.com/RapidOCR/NcnnBuilder/releases/download/${{ env.NCNN_VERSION }}/${{ env.GPU_PKG_NAME }}.7z -O ${{ env.GPU_PKG_NAME }}.7z
          7z x ${{ env.GPU_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          wget https://github.com/RapidOCR/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -O ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          export VULKAN_SDK=`pwd`/vulkansdk-macos-1.2.162.0/macOS
          chmod a+x build-default.sh &&./build-default.sh

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir macos-bin
          cp scripts/run-benchmark-cn.sh macos-bin/run-benchmark-cn.sh
          cp scripts/run-test-cn.sh macos-bin/run-test-cn.sh
          cp -r images macos-bin/images
          mv Darwin-bin-cpu/install/bin macos-bin/Darwin-bin-cpu
          mv Darwin-bin-gpu/install/bin macos-bin/Darwin-bin-gpu
          7z a macos-bin.7z macos-bin
          mkdir macos-jni
          mv Darwin-jni-cpu/install/sharedlib macos-jni/Darwin-jni-cpu
          mv Darwin-jni-gpu/install/sharedlib macos-jni/Darwin-jni-gpu
          7z a macos-jni.7z macos-jni

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: macos-bin
          path: macos-bin.7z

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: macos-jni
          path: macos-jni.7z